# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "wireguard", "fastd" ]
  pull_request:
    branches: [ "wireguard", "fastd" ]

  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_gluon:
    runs-on: ubuntu-latest
    steps:
      - name: Running jenkins job 'ffkbu-multihood-stable-${{ github.base_ref }}-gluon2021.X-ci'
        uses: Mondtic/build-jenkins-job@master
        with:
          jenkins-url: https://jenkins.kbu.freifunk.net
          jenkins-token: ${{ secrets.JENKINS_CI_TOKEN }}
          jenkins-user: ${{ secrets.JENKINS_CI_USER }}
          jenkins-job: ffkbu-multihood-stable-${{ github.base_ref }}-gluon2021.X-ci
          jenkins-wait-job: "wait"
          jenkins-ssl-verify: "true"
          jenkins-job-params: '{"SITEBRANCH": "${{ github.head_ref }}"}'